version: '3'

services: 

  app:
    build: 
      context: node
    container_name: app
    networks: 
      - node-network
    volumes: 
      - usr/src/app
    restart: always
    tty: true
    ports: 
      - "3000:3000"
    depends_on: 
      - nginx
      - db
  
  nginx:
    build:
      context: ./nginx
    container_name: nginx
    networks:
      - node-network
    ports:
      - "8080:80"
    depends_on:
      - db

  db:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    tty: true
    volumes: 
      - ./sql:/docker-entrypoint-initdb.d
    environment: 
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - "3308:3306"
    networks: 
      - node-network

networks: 
  node-network:
    driver: bridge      